### ISSUE TITLE
The dataset is lack of  "clear_sig.mat" files 

### ISSUE THREAD

**Issue by Jimmyshi7** [OzerCanDevecioglu/Blind-ECG-Restoration-by-Operational-Cycle-GANs#2]
There are not "clear_sig.mat" files in the "all_patients" folder  when I run "test.py". Could you please share these files?
![aa9a0d02b382d8212f53e65eb16e87d](https://user-images.githubusercontent.com/34163627/168038343-422f17b1-b7fd-4e69-a22b-e2e3cee87446.png)

**Comment by zpuser1** [comment]
I have the same problem, have you solved it?

**Comment by Arpita1817** [comment]
I, too, have the same issue. Where can we find the clean_sig.mat for testing?

**Comment by OzerCanDevecioglu** [comment]
Hi, sorry for the late reply. The code is updated
